<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <UserSecretsId>0874a62d-f17e-4fa8-936d-8dacba55ee95</UserSecretsId>
        <RootNamespace>Npgmq.Test</RootNamespace>
        <LangVersion>default</LangVersion>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper"  />
        <PackageReference Include="DeepEqual"  />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"  />
        <PackageReference Include="xunit.runner.visualstudio" >
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Xunit.SkippableFact"  />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Npgmq\Npgmq.csproj" />
    </ItemGroup>
</Project>
