name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
  workflow_dispatch:

env:
  VERSION: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}  # This checks out the commit that triggered the workflow run

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Set the version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Print the version
        run: echo $VERSION

      - name: Restore dependencies
        run: dotnet restore

      - name: Verify Format
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=${{ env.VERSION }} /p:CopyrightYear=$(date +%Y)

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pgmq-version:
          - latest
          - 1.11.1
          - 1.11.0
          - 1.10.0
          - 1.9.0
          - 1.8.1
          - 1.8.0
          - 1.7.0
          - 1.6.1
          - 1.6.0
          - 1.5.1
    name: Test pgmq ${{ matrix.pgmq-version }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}  # This checks out the commit that triggered the workflow run

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Test
        run: Npgmq.Test/scripts/run-tests.sh ${{ matrix.pgmq-version }}

  pack:
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}  # This checks out the commit that triggered the workflow run

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Set the version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack Npgmq/Npgmq.csproj --configuration Release /p:Version=${{ env.VERSION }} /p:PackageVersion=${{ env.VERSION }} /p:CopyrightYear=$(date +%Y) --output out

      - uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: out

  publish:
    needs: pack
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build-artifact
          path: out

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Push
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
